// Generated by https://quicktype.io

export interface Videos {
  activityType: string;
  createdAt:    string;
  endTime:      number;
  idActivity:   string;
  idCreator:    string;
  idProject:    string;
  startTime:    number;
  updatedAt:    string;
  urlVideo:     string;
  timestamps:   Timestamp[];
}

export interface Timestamp {
  activities: Activities;
  time:       number;
  type:       string;
}

export interface Activities {
  correctAnswer:    string;
  incorrectAnswer1: string;
  question:         string;
  justification:    string;
  incorrectAnswer3: string;
}
